- name: Ensure portainer is running
  community.docker.docker_compose:
    project_src: "/home/{{ username }}/docker-images/portainer"
    build: no
    env_file: "/home/{{ username }}/docker-images/.env"