- name: Ensure additional docker volumes for user home folders are created
  docker_volume:
    name: "samba-{{ item }}"
  loop: "{{ samba.users | map(attribute='name') }}"

- name: Ensure samba docker-compose.yml file is generated properly from template
  template:
    src: "./files/docker-images/samba/docker-compose.yml.j2"
    dest: "/home/{{ username }}/docker-images/samba/docker-compose.yml"

- name: Ensure samba config.yml file is generated properly from template
  template:
    src: "./files/docker-images/samba/config.yml.j2"
    dest: "/home/{{ username }}/docker-images/samba/config.yml"

- name: Ensure samba password files for docker secrets exist
  file:
    path: "/home/{{ username }}/docker-images/samba/sensitive/{{ item }}_password.txt"
    state: touch
    modification_time: preserve
    owner: "{{ username }}"
    group: "docker"
  with_items: "{{ samba.users | map(attribute='name') }}"

- name: Ensure samba password files for docker secrets contain secrets
  lineinfile:
    dest: "/home/{{ username }}/docker-images/samba/sensitive/{{ item.name }}_password.txt"
    regexp: "^$"
    line: "{{ item.password }}"
  with_items: "{{ samba.users }}"

#- name: Ensure samba is running
#  community.docker.docker_compose:
#    project_src: "/home/{{ username }}/docker-images/samba"
#    build: no
