- name: Ensure school-docs repo is up to date
  git:
    repo: "https://github.com/JaninaWibker/school-docs"
    dest: "/home/{{ username }}/docker-images/school-docs/repo"
    single_branch: yes
    version: main

- name: Ensure school-docs is running
  community.docker.docker_compose:
    project_src: "/home/{{ username }}/docker-images/school-docs"
    build: yes
    env_file: "/home/{{ username }}/docker-images/.env"
