- name: Ensure docker-image files are present
  become: no
  ansible.posix.synchronize:
    src: "./files/docker-images"
    dest: "/home/{{ username }}/"
    private_key: "{{ ansible_ssh_private_key_file }}"
    use_ssh_args: yes
    archive: no
    recursive: yes
    checksum: yes
    rsync_opts:
      - "--exclude=.env"                           # this uses a template (this file)
      - "--exclude=gitea/app.ini.j2"               # this uses a template (containers/gitea.yml)
      - "--exclude=bind9/zones/db.box.j2"          # this uses a template (containers/bind9.yml)
      - "--exclude=bind9/named.conf.options.j2"    # this uses a template (containers/bind9.yml)

- name: Ensure .env file for docker-compose is generated
  template:
    src: "./files/dotenv.j2"
    dest: "/home/{{ username }}/docker-images/.env"

- name: Ensure docker volumes are created
  docker_volume:
    name: "{{ item }}"
  loop:
    - gitea-data
    - portainer-data
    - vaultwarden-data
    - traefik-logs
    - traefik-certs

- name: Ensure docker network is created
  docker_network:
    name: my-bridge

- import_tasks: ./tasks/containers/bind9.yml
#- import_tasks: ./tasks/containers/bitwarden.yml
- import_tasks: ./tasks/containers/gitea.yml
#- import_tasks: ./tasks/containers/traefik.yml
