- name: Ensure docker-image files are present
  become: no
  ansible.posix.synchronize:
    src: "./files/docker-images"
    dest: "/home/{{ username }}/"
    private_key: "{{ ansible_ssh_private_key_file }}"
    use_ssh_args: yes
    archive: no
    recursive: yes
    checksum: yes
    rsync_opts:
      - "--exclude=.env"                           # this uses a template (this file)
      - "--exclude=gitea/app.ini.j2"               # this uses a template (containers/gitea.yml)
      - "--exclude=bind9/zones/db.box.j2"          # this uses a template (containers/bind9.yml)
      - "--exclude=bind9/named.conf.options.j2"    # this uses a template (containers/bind9.yml)
      - "--exclude=samba/docker-compose.yml.j2"    # this uses a template (containers/samba.yml)
      - "--exclude=samba/config.yml.j2"            # this uses a template (containers/samba.yml)
      - "--exclude=samba/sensitive/*_password.txt" # this uses lineinfile (containers/samba.yml)
      - "--exclude=website/repo"                   # this uses git role   (containers/website.yml)
      - "--exclude=school-docs/repo"               # this uses git role   (containers/school-docs.yml)

- name: Ensure .env file for docker-compose is generated
  template:
    src: "./files/dotenv.j2"
    dest: "/home/{{ username }}/docker-images/.env"

- name: Ensure docker volumes are created
  docker_volume:
    name: "{{ item }}"
  loop:
    - gitea-data
    - plex-movies
    - plex-shows
    - plex-config
    - plex-transcode
    - photoprism-images
    - photoprism-imports
    - photoprism-data
    - photoprism-db-data
    - portainer-data
    - samba-drop
    - samba-public
    - samba-studium
    - vaultwarden-data
    - traefik-logs
    - traefik-certs
    - kuma-data

- name: Ensure docker network is created
  docker_network:
    name: my-bridge

- import_tasks: ./tasks/containers/bind9.yml
#- import_tasks: ./tasks/containers/bitwarden.yml
- import_tasks: ./tasks/containers/gitea.yml
- import_tasks: ./tasks/containers/kuma.yml
- import_tasks: ./tasks/containers/photoprism.yml
- import_tasks: ./tasks/containers/plex.yml
- import_tasks: ./tasks/containers/portainer.yml
- import_tasks: ./tasks/containers/samba.yml
- import_tasks: ./tasks/containers/school-docs.yml
- import_tasks: ./tasks/containers/traefik.yml
- import_tasks: ./tasks/containers/website.yml
