services:
  traefik:
    image: "traefik:v2.5"
    container_name: traefik
    ports:
      #- "8080:8080" # dashboard
      - "80:80"     # http (redirects to https)
      - "443:443"   # https
    volumes:
      - ./traefik.yaml:/traefik.yaml
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-certs:/letsencrypt
      - traefik-logs:/logs
    labels:
      - "traefik.enable=true"
      #- "traefik.http.routers.dashboard.rule=Host(`${BASE_URL}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      #- "traefik.http.routers.dashboard.entryPoints=dashboard"
      #- "traefik.http.routers.dashboard.service=api@internal"
      #- "traefik.http.routers.dashboard.middlewares=dashboard-auth"
      #- "traefik.http.routers.dashboard.tls.certresolver=leresolver"
      #- "traefik.http.middlewares.dashboard-auth.basicauth.usersFile=/etc/traefik/auth"
      - "lighthouse.base=traefik:v2.5"
    networks:
      - infra-network
    restart: always
    logging:
      driver: journald

networks:
  infra-network:
    external: true
    name: my-bridge

volumes:
  traefik-certs:
    external: true
    name: "traefik-certs"
  traefik-logs:
    external: true
    name: "traefik-logs"
