version: '3.5'

services:
  website:
    image: website:1.0.3
    container_name: website
    build: repo
    restart: unless-stopped
    networks:
      - infra-network
    ports: [] # port 3000 is used by default
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.website.loadbalancer.server.port=3000"
      - "traefik.http.routers.website.rule=Host(`${BASE_URL}`) || Host(`www.${BASE_URL}`) || Host(`web.box`)"
      - "traefik.http.routers.website.entrypoints=websecure"
      - "traefik.http.routers.website.tls=true"
      - "traefik.http.routers.website.tls.certresolver=leresolver"


networks:
  infra-network:
    external: true
    name: my-bridge
