services:
  website-janina:
    image: website-janina
    container_name: website-janina
    build: repo
    restart: unless-stopped
    networks:
      - infra-network
    ports: [] # port 80 is used by default
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.website-janina.loadbalancer.server.port=80"
      - "traefik.http.routers.website-janina.rule=Host(`${BASE_URL}`) || Host(`www.${BASE_URL}`)"
      - "traefik.http.routers.website-janina.entrypoints=websecure"
      - "traefik.http.routers.website-janina.tls=true"
      - "traefik.http.routers.website-janina.tls.certresolver=leresolver"


networks:
  infra-network:
    external: true
    name: my-bridge
